### ISSUE TITLE
Commit Cargo.lock file to version control

### ISSUE THREAD

**Issue by beeb** [KevinWh0/Hourly-Wallpaper#1]
Hey there! As discussed on Mastodon, I will create a few issues with suggestions for your project.

The first is to commit the cargo.lock file to version control. It's useful to make sure your builds are reproducible.

[docs](https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html):

>  If you’re building an end product, which are executable like command-line tool or an application, or a system library with crate-type of staticlib or cdylib, check Cargo.lock into git.

**Comment by ChaoticLeah** [comment]
Done!
