### ISSUE TITLE
Unused crate/derive

### ISSUE THREAD

**Issue by beeb** [KevinWh0/Hourly-Wallpaper#10]
This "strum" stuff seems unused:

https://github.com/KevinWh0/Hourly-Wallpaper/blob/474f508794b5f889c68ff6e2a0eb3656b0adcd42/src/api/wallpaper_api_config.rs#L9-L11

**Comment by ChaoticLeah** [comment]
That was there so it was case insensitive in the config. For now I reverted that but missed that. I commented it out just incase I change it back

**Comment by beeb** [comment]
You can also comment out the `EnumString` that actually implements the unneeded methods to convert the enum to string.
