### ISSUE TITLE
Avoid some type casting 

### ISSUE THREAD

**Issue by beeb** [KevinWh0/Hourly-Wallpaper#11]
I notice you used i32 as the type for Resolution. This makes little sense as resolution needs to be positive. I suggest you change the type of w and h in Resolution (from the api mod) to unsigned integer and then use that struct in place of the one I had written (didn't notice you already had one defined for the api) in the Config struct. That way you can avoid "as i32" in a couple of places and reduce code duplication.

**Comment by ChaoticLeah** [comment]
Oh I just saw this now, but I already did this thanks to cargo. Also I am now using 1 struct as well for Resolution.
