### ISSUE TITLE
Suggestion: use serde for parsing the config file

### ISSUE THREAD

**Issue by beeb** [KevinWh0/Hourly-Wallpaper#2]
Since you already depend on `serde` for the wallpaper API, I would encourage you to use it for parsing the YAML config file. 

This would allow to define the structure of your config data and avoid having to `get` and `unwrap` every time you want to access something. If serde can parse your file into your config struct, then you will know for sure all the keys are present and of the right type.

It might look something like this (untested):

```rust
#[derive(Deserialize)]
struct Resolution {
    w: usize,
    h: usize,
}

#[derive(Deserialize)]
//#[serde(rename_all="camelCase")] // this could be used if all your keys have the wrong case (from an API for example)
struct Config {
    #[serde(rename="apiKey")]
    api_key: String, // note the snake_case is the preferred case in rust, but if you need to keep camelCase in your config you can map it
    purity: Purity, // your enum
    new_picture_delay: Option<usize>, // you can mark keys as optional using an `Option` if you want
    min_resolution: Resolution,
    query_data: Vec<Query>, // you already have a Query struct defined, just need to derive Deserialize on it
}

fn load_config() -> Result<Config, Box<dyn Error>> {
    let config_file_string = fs::read_to_string("config.yaml")?;
    let config: Config = serde_yaml::from_str(&config_file_string)?; // you need to add serde_yaml as a dependency
    Ok(config)
}
```

**Comment by beeb** [comment]
Note that to deserialize into the enum, you will need `#[serde(rename_all = "UPPERCASE")]` (if you want the variants to be uppercase in the YAML file) and `Deserialize` derived on the `Purity` enum (which should have PascalCase variants to match the rust style guidelines).

**Comment by beeb** [comment]
This is how your `get_random_query` might look after this change (untested, but note you need to derive `Clone` on your `Query` struct):

```rust
fn get_random_query(config: &Config) -> Query {
    let Some(rand_query_data) = config.query_data.choose(&mut rand::thread_rng()) else { // neat let-else syntax (available since rust 1.65)
        return Query {
            query: "".to_string(),
            categories: "".to_string(),
        };
    };
    rand_query_data.clone()
}
```

**Comment by beeb** [comment]
You might want to return a `Result` in `get_random_query` if it's not acceptable that the config file doesn't provide at least 1 query. In which case you would use the question mark operator after the `choose()` to avoid using `if`

**Comment by ChaoticLeah** [comment]
Probably will put this all in a src/config.rs or src/configManager.rs file

**Comment by ChaoticLeah** [comment]
Did all of this!

**Comment by beeb** [comment]
Gotta love serde :D See how much simpler your code got?
