### ISSUE TITLE
About mods, use, etc.

### ISSUE THREAD

**Issue by beeb** [KevinWh0/Hourly-Wallpaper#3]
So in your project you have an `api` mod which contains a `wallpaper_api_config` sub-module and `wallpaper` sub-module.

In your `api/mod.rs` you do this:

```rust
use self::wallpaper::Wallpaper;
pub mod wallpaper_api_config;
pub mod wallpaper;
```

which I would change to this

```rust
pub mod wallpaper;
pub mod wallpaper_api_config;

use reqwest::{
    header::{ACCEPT, CONTENT_TYPE, USER_AGENT},
    StatusCode,
};

use self::{ // note the self is needed because you also have a crate named `wallpaper`. Otherwise you could directly use `wallpaper` as the first path segment
    wallpaper::Wallpaper,
    wallpaper_api_config::{Purity, WallpaperAPIConf},
};
```

Allowing you to write `WallpaperApiConf` and `Purity` (in your match) directly without the path before. Similarly, you could do `header(CONTENT_TYPE)` without the full path to reqwest, etc.

**Comment by beeb** [comment]
You can also re-export things from a sub-module into its parent so that it's easier to access from, for example, main.rs :

```rust
// inside api/mod.rs
pub use self::wallpaper_api_config::Purity;
```

Now in main.rs you can do:

```rust
use api::Purity;

struct Config {
    //...
    purity: Purity // instead of api::wallpaper_api_config::Purity
}
```

**Comment by ChaoticLeah** [comment]
I think the last push should cover all this, but I'm not totally sure.

Ill close it when you confirm that its all been done

**Comment by beeb** [comment]
Sure it's anyway all suggestions. Whenever you feel like it's too verbose to call function/enums including their full module path, you can add a `use` statement to bring them into scope and shorten how you call them. I'll check again for more suggestions when you have moved to serde_yaml (which is you main problem at the moment since not using it adds a lot of complexity).

**Comment by beeb** [comment]
I think you got the gist of it, I hope you now understand how `use` is used and what `mod` does!

On a side note, the `crate::` is optional here:

https://github.com/KevinWh0/Hourly-Wallpaper/blob/1de115e6211db27cf98f68865f71e0b3293b8ef0/src/main.rs#L3

because `config_manager` is a direct child of your root (main)

In my code in general, I try to avoid having `::` when I call functions from other modules or crates in general, so I put a lot of `use` statements at the top, to bring into scope what I will use. But it's a matter of preferrence, some people prefer having fewer `use` and more verbose calls.

**Comment by beeb** [comment]
For instance, imagine this monstrosity without having all the `use` at the top to bring the `nom` functions into scope:

https://github.com/beeb/aoc-2022/blob/237cc1c5b910d9e4155b479f8526962204cb61e1/src/days/day01.rs#L16-L21
