### ISSUE TITLE
`new` in `WallpaperAPIConf` should be located in the Builder struct

### ISSUE THREAD

**Issue by beeb** [KevinWh0/Hourly-Wallpaper#4]
You have this:

https://github.com/KevinWh0/Hourly-Wallpaper/blob/a966c0e177ac903ada68b26a3535c80f98facb69/src/api/wallpaper_api_config.rs#L36-L44

Which is not idiomatic, as the `new` method usually created an instance of `Self` (so in your case it would create a `WallpaperAPIConf` directly).
Since you are creating a builder, you should move this `new` method into the `impl WallpaperAPIConfBuilder`.

The function could then be changed to: 

```rust
    pub fn new_builder() -> Self {
        Self {
            query: "".to_string(),
            min_resolution: Resolution { w: 1920, h: 1080 },
            categories: "".to_string(),
            purity: Purity::SFW,
            api_key: "".to_string(),
        }
    }
```

**Comment by ChaoticLeah** [comment]
Haha yeah I was meaning to change that and forgot. Easy fix. Not sure how it got there in the first place.

**Comment by ChaoticLeah** [comment]
I think I found some sample code like that so assumed it was perhaps a rust thing, anyways its fixed now
