### ISSUE TITLE
cargo clippy

### ISSUE THREAD

**Issue by beeb** [KevinWh0/Hourly-Wallpaper#5]
You can run `cargo clippy` in your shell to get nice suggestions for code improvements.

For instance, with the latest rust compiler (1.66), I see that you have a `format in format` warning in `api/mod.rs`, which could be combined:

```rust
    search.push_str(&format!(
        "atleast={}x{}&",
        args.min_resolution.w,
        args.min_resolution.h
    ));
```

**Comment by beeb** [comment]
Also instead of constructing your query string by hand, you could use https://docs.rs/reqwest/latest/reqwest/struct.Url.html#method.parse_with_params

Or at the moment when you make the request with https://docs.rs/reqwest/latest/reqwest/struct.RequestBuilder.html#method.query

**Comment by ChaoticLeah** [comment]
Alright I have cleaned up all the issues Clippy had with this project, and have moved to using https://docs.rs/reqwest/latest/reqwest/struct.Url.html#method.parse_with_params

**Comment by beeb** [comment]
Keeping the best (using serde_yaml) for last I see :)
