### ISSUE TITLE
Return Result from main

### ISSUE THREAD

**Issue by beeb** [KevinWh0/Hourly-Wallpaper#6]
Since you use tokio, you can return a `Result<(), Box<dyn Error>>` from your main() so that you can use the `?` operator instead of panicking in 

https://github.com/KevinWh0/Hourly-Wallpaper/blob/86d63cc084a6b65441be6cf541f58bfa363a74e3/src/main.rs#L13-L17

```rust
let config = config_manager::load_config().await?;
```

**Comment by beeb** [comment]
Likewise, I would refactor the `set_wallpaper`, a faillible operation, to return `Result`:

```rust
    pub fn set_wallpaper(&self) -> Result<(), Box<dyn Error>> {
        let wallpaper_path = env::temp_dir().join("wallpaper.png");
        wallpaper::set_from_path(wallpaper_path.as_os_str().to_str().ok_or("Invalid path")?)?;
        wallpaper::set_mode(wallpaper::Mode::Crop)?;
        Ok(())
    }
```

Here I avoided all unwraps by using the `?` on Results, as well as converting the `Option<&str>` given by `as_os_str().to_str()` into a `Result<&str, Error>` with `ok_or()` and then unwrapping the `Result` with `?`

**Comment by ChaoticLeah** [comment]
Done, wanted to keep errors clear so I modified your suggested set_wallpaper
