### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by beeb** [KevinWh0/Hourly-Wallpaper#7]
In this part: 

https://github.com/KevinWh0/Hourly-Wallpaper/blob/86d63cc084a6b65441be6cf541f58bfa363a74e3/src/api/wallpaper.rs#L51-L55

I personally hate the `if let` on the RHS of an assignment. I would do it like this:

```rust
        let mut wallpaper_path = env::temp_dir();
        wallpaper_path.push("wallpaper.png");
        let mut file: File = File::create(wallpaper_path) // no need to go through a regular string or even OsStr, since PathBuf is accepted by tokio
            .await
            .map_err(|_| "Failed to create file in temp dir")?;
```

**Comment by beeb** [comment]
If the `create` was not async, you could even use the `and_then()` combinator to make it a bit shorter, but async closures are not stable.

**Comment by beeb** [comment]
Actually I think I can do better:

```rust
        let wallpaper_path = env::temp_dir().join("wallpaper.png"); // no mutable variable
        let mut file: File = File::create(wallpaper_path) // no need to go through a regular string or even OsStr, since PathBuf is accepted by tokio
            .await
            .map_err(|_| "Failed to create file in temp dir")?;
```

**Comment by ChaoticLeah** [comment]
Done! Interesting learning about closures. Seems almost like lambdas!

**Comment by beeb** [comment]
Yeah, rust borrows a lot from functional languages and I love it
