### ISSUE TITLE
Avoid panics

### ISSUE THREAD

**Issue by beeb** [KevinWh0/Hourly-Wallpaper#8]
I would remove all `panic!` calls and instead return `Result` in the function. That way, you can bubble up errors with `?` all the way to your `main()` which itself can return a `Result` which will finally cause the program to panic in case of error.

That way, you can handle errors accordingly at any level an potentially recover from some errors.

**Comment by beeb** [comment]
In the case of `get_wallpaper_url_from_request_url` you can even return a `Result<Option<Wallpaper>, Box<dyn Error>>` in order to express that the operation can fail, or can return a valid wallpaper, or can return no wallpaper (which is not considered a failure apparently).

Also, you can skip the last `if` in this function by using:

```rust
return api_response.data.get(0).map(|wallpaper| wallpaper.to_owned());
```

In this case it return the None if None, but maps the "Some" (a reference) to another "Some" (an owned value). The combinators are great to reduce nesting.

**Comment by ChaoticLeah** [comment]
return no wallpaper wasn't considered a failure since next go it could pick another query and set the background.

**Comment by ChaoticLeah** [comment]
All panics have been avoided now
