### ISSUE TITLE
Enable format on save?

### ISSUE THREAD

**Issue by beeb** [KevinWh0/Hourly-Wallpaper#9]
Some weird formatting can be seen in your files. Is your IDE/editor formatting your code on save with rustfmt? Mostly spacing and line returns in weird places.

**Comment by ChaoticLeah** [comment]
I think it should be formatted in the latest push. Had to enable format on save though I think its using prettier at the moment.

**Comment by beeb** [comment]
yep all good now. It's not using prettier, if you have rust-analyzer setup then it's using rustfmt (in my vscode, prettier has an icon next to it that says it's disabled)
